### ISSUE TITLE
[Compile Error] Missing 'atlbase.h' when compile ShaderCompiler

### ISSUE THREAD

**Issue by whaleeej** [JX-Master/LunaGB#1]
Here attached the error message
---------------------------------------------------------------------------------------------------------------------------------------------
error: ShaderCompiler.cpp
C:\Users\ceej_\Desktop\LunaGB\SDKs\dxc\windows\include\dxc/Support/WinIncludes.h(43): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory

  > in Modules\Luna\ShaderCompiler\Source\ShaderCompiler.cpp
warning: You are working in the project directory(C:\Users\ceej_\Desktop\LunaGB) and you can also
force to build in current directory via run `xmake -P .`
---------------------------------------------------------------------------------------------------------------------------------------------
installing v142 C++ ATL(x84 and x64) does not help

Appreciate your help!

**Comment by JX-Master** [comment]
Open Visual Studio Installer and check whether you have installed multiple versions of Visual Studio (including Visual Studio Build Tools), and remove the version you don't need, or install ATL on all versions of Visual Studio.

**Comment by whaleeej** [comment]
> Open Visual Studio Installer and check whether you have installed multiple versions of Visual Studio (including Visual Studio Build Tools), and remove the version you don't need, or install ATL on all versions of Visual Studio.

The only Visual Studio i installed is 2019, which i have tried both ATL v141 and v142. Neither successed.

FYI. The Error output is 
1>EXEC : error : ShaderCompiler.cpp
1>C:\Users\ceej_\Desktop\LunaGB\SDKs\dxc\windows\include\dxc\Support\WinIncludes.h(43): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory

Appreciate it if you can provide more info about visual studio env!

Regards
